default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  username: developer
  password: devKey

development:
  <<: *default
  database: photoart_dev

test:
  <<: *default
  database: photoart_test

production:
  <<: *default
  database: photoart
