default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  username: photouser
  password: photopass
  database: photodb

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
